export const COMPANY_EXPERIENCE = [
  {
    name: "Onlinesales.ai",
    logo: "./src/assets/onlinesalesai_logo.jpg",
    role: "Software Engineer (Frontend)",
    duration: "June 2024 - Jan 2025",
    technologies: [
      "React",
      "JavaScript",
      "TypeScript",
      "HTML",
      "CSS",
      "Bootstrap",
      "Strapi",
      "Node.js",
    ],
    workDone: [
      "Worked on AdTech Product",
      "Developed different features and components, helped with the integration of Highcharts and React TanStack",
      "Added download functionality for all charts and tables, ensuring all reports are downloadedable.",
      "Built an API comparison automation script using Node.js, triggered by a cron job, to ensure data consistency across different databases and Strapi. If discrepancies were found, the script automatically updated the data, reducing manual work by 50%.",
      "Integrated Strapi, Microsoft Clarity, and Pendo in the Platform.",
      "Conducted interviews for Frontend Developer roles, conducted code reviews, assisted in oncall for fixing high priority bugs and helped managing the QA team in building and implementing automation solutions.",
    ],
  },
  {
    name: "Onlinesales.ai",
    logo: "./src/assets/onlinesalesai_logo.jpg",
    role: "Technical Intern (Frontend)",
    duration: "Aug 2023 - May 2024",
    technologies: [
      "React",
      "JavaScript",
      "TypeScript",
      "HTML",
      "CSS",
      "Bootstrap",
      "Strapi",
      "Node.js",
    ],
    workDone: [
      "Helped in increasing the performance in the product, improved the batch calls and API request calls to decrease the unwanted requests.",
      "Made a custom targeting feature with the help of strapi where user can do retail media targeting using there own preferences.",
    ],
  },
  {
    name: "PHN Technology Pvt Ltd",
    logo: "./src/assets/phn_logo.jpg",
    role: "AIML & Robotics Intern",
    duration: "June 2023 - July 2023",
    technologies: [
      "Python",
      "OpenCV",
      "TensorFlow",
      "IoT",
      "Raspberry Pi",
      "Machine Learning",
    ],
    workDone: [
      "Developed an AI model for object recognition using YOLOv5.",
      "Built Arduino-based IoT robots for real-world applications.",
    ],
  },
];

export const PROJECTS = [
  {
    name: "DocSnap: Chrome Extension",
    technologies: ["React", "OAuth", "Google APIs"],
    description: "A Chrome extension for adding bullet point notes to Google Docs just by right clicking the text from any webpage.",
    source: "https://chromewebstore.google.com/detail/docsnap/dkdjpfmbnjglmffmceeeadplmbjmfhob",
    image: "./src/assets/docSnap.png",
    date: "February 2025",
  },
  {
    name: "Todo App with JsonBlob",
    technologies: ["React", "TypeScript", "Tailwind CSS"],
    description: "A simple todo app built using React and JsonBlob for storing the data.",
    source: "https://todo-jsonblob.netlify.app/",
    image: "./src/assets/todo-app.png",
    date: "March 2025",
  },
  {
    name: "Encoder-Decoder Hub",
    technologies: ["React", "JavaScript", "HTML", "CSS"],
    description: "A web app for text encoding and decoding strings with pretty output.",
    source: "https://encoder-decoder-hub.netlify.app/",
    image: "./src/assets/encoder-decoder-hub.png",
    date: "November 2024",
  },
  {
    name: "PawDoption: Pet Adoption Website",
    technologies: ["React", "Node.js", "MongoDB", "Express"],
    description: "A pet adoption website built the frontend as well as the backend using MERN stack.",
    source: "https://pet-adoption-website-liard.vercel.app/",
    image: "./src/assets/pet-adoption.png",
    date: "April 2024",
  },
]